/**
 * HTTPS Proxy for PWA support
 * - Reads cert.pem + cert-key.pem generated by OpenSSL (via start-https.ps1)
 * - Proxies all HTTPS requests on port 3000 → HTTP Next.js on port 3001
 *
 * Usage:
 *   node https-proxy.mjs
 *
 * Install cert.pem on your device as a trusted root CA to dismiss the
 * "Not Secure" warning and enable PWA installation.
 */

import https from 'https';
import http from 'http';
import { readFileSync } from 'fs';

const NEXT_PORT = 3001;   // Internal Next.js port
const HTTPS_PORT = 3000;  // Public-facing HTTPS port
const PUBLIC_IP = '212.64.201.208';

// ── Load cert ────────────────────────────────────────────────────────────────
let key, cert;
try {
  key  = readFileSync('./cert-key.pem', 'utf8');
  cert = readFileSync('./cert.pem', 'utf8');
} catch {
  console.error('HATA: cert.pem veya cert-key.pem bulunamadı.');
  console.error('Lütfen start-https.ps1 script\'ini çalıştırın.');
  process.exit(1);
}

// ── HTTPS → HTTP proxy ───────────────────────────────────────────────────────
const server = https.createServer({ key, cert }, (req, res) => {
  const opts = {
    hostname: '127.0.0.1',
    port: NEXT_PORT,
    path: req.url,
    method: req.method,
    headers: {
      ...req.headers,
      'x-forwarded-proto': 'https',
      'x-forwarded-host': req.headers.host || PUBLIC_IP,
      host: `127.0.0.1:${NEXT_PORT}`,
    },
  };

  const proxy = http.request(opts, (proxyRes) => {
    res.writeHead(proxyRes.statusCode, proxyRes.headers);
    proxyRes.pipe(res, { end: true });
  });

  proxy.on('error', (err) => {
    console.error('Proxy hatası:', err.message);
    if (!res.headersSent) {
      res.writeHead(502);
      res.end('Next.js sunucusuna ulaşılamıyor.');
    }
  });

  req.pipe(proxy, { end: true });
});

server.listen(HTTPS_PORT, '0.0.0.0', () => {
  console.log(`\n✅ HTTPS Proxy çalışıyor`);
  console.log(`   Dışarıya açık : https://${PUBLIC_IP}:${HTTPS_PORT}`);
  console.log(`   → Next.js     : http://127.0.0.1:${NEXT_PORT}`);
  console.log(`\n⚠️  Tarayıcıda ilk açılışta "Güvenli değil" uyarısı çıkacak.`);
  console.log(`   cert.pem cihaza güvenilir kök CA olarak yüklendikten sonra PWA kurulumu çalışır.\n`);
});
